export enum ActionType {
  SEARCH_PACKAGES = 'SEARCH_PACKAGES',
  SEARCH_PACKAGES_SUCCESS = 'SEARCH_PACKAGES_SUCCESS',
  SEARCH_PACKAGES_FAILURE = 'SEARCH_PACKAGES_FAILURE',
  SEARCH_PACKAGE_DETAIL = 'SEARCH_PACKAGES',
  SEARCH_PACKAGE_DETAIL_SUCCESS = 'SEARCH_PACKAGES_SUCCESS',
  SEARCH_PACKAGE_DETAIL_FAILURE = 'SEARCH_PACKAGES_FAILURE',
}